using System.Runtime.CompilerServices;
using LoreFetch.Core.Abstractions;
using LoreFetch.Core.Collection;
using LoreFetch.Core.Detection;
using LoreFetch.Core.Export;
using LoreFetch.Core.Fakes;
using LoreFetch.Core.Identification;
using LoreFetch.Core.Scanning;
using LoreFetch.Lab;
using LoreFetch.Lab.Images;
using LoreFetch.Lab.Synthetic;
using Microsoft.Extensions.Logging.Abstractions;
using OpenCvSharp;

namespace LoreFetch.Tests.Integration.EndToEnd;

/// Package I2+I3: the detector/rectifier/identifier/catalog slots are now
/// the real classes, constructed over the COMMITTED index
/// (<c>data/index/cards.lfidx</c>) exactly the way
/// <see cref="LoreFetch.App.AppComposition"/> composes Real mode (docs/
/// docs/history/orchestration-plan.md §4, the I2/I3 override). The store and both
/// exporters stay as package I1 wired them.
///
/// The one thing this set cannot do literally is honour an arbitrary
/// caller-supplied "distances" list the way <see cref="FakeImplementationSet"/>
/// does — <see cref="HashCardIdentifier"/> reports whatever a real hash
/// comparison actually measures, not a scripted number. So the FRAME
/// CONTENT is what this set controls instead: <see cref="CreateIdentifier"/>
/// (the one call every existing end-to-end case already makes right before
/// starting the pipeline) writes real Scryfall-card imagery — generated by
/// B7's <see cref="SyntheticFrameGenerator"/>/B6's
/// <see cref="MultiCardFrameGenerator"/> from a render pulled out of the
/// local Scryfall cache, so the rendered artwork IS in the committed index
/// — into the frame folder <see cref="CreateFrameSourceFactory"/> already
/// opened, choosing genuine matching content when the requested distance
/// reads as "this tile should land as a confident/low-confidence match" and
/// genuinely non-matching content (a flat, high-contrast card-shaped patch
/// with no real artwork) when it reads as "this tile should be Unresolved".
/// Every existing case's assertions are therefore exercised for real: a
/// real detector finds a real card-shaped quad, a real rectifier warps it,
/// and the real committed index either does or does not recognise it —
/// nothing here fabricates a `CardCandidate.Distance` or an `OracleId`.
///
/// Gated (orchestration finding V7): missing repo root, missing committed
/// index/thresholds, or a missing/incomplete Scryfall cache is an honest
/// skip via <see cref="RealArtifactGate"/> — or, under
/// <c>LOREFETCH_REQUIRE_REAL=1</c>, a failure — never a silent fallback to
/// fake behaviour.
public sealed class RealImplementationSet : IImplementationSet
{
    /// DECISIONS.md's 2026-09-22 ruling: "15in only" — the one geometry this
    /// integration package generates synthetic frames at, matching the
    /// committed goodDistance/okDistance (208/240), which were themselves
    /// calibrated from a 15in fixture corpus.
    private const float HeightInches = 15f;

    /// Every EndToEndTests case requests either ~90 ("GoodDistance-10" in
    /// its own local 100/200 thresholds — wants a confident/low-confidence
    /// match) or ~250 ("OkDistance+50" — wants Unresolved). This set cannot
    /// honour either number literally (see the type's own doc comment), so
    /// it reads the requested value as an INTENT instead: anything comfortably
    /// below the committed thresholds.json ceiling for a genuine match (208)
    /// reads as "make this tile match for real"; anything at or above it
    /// reads as "make this tile genuinely fail to match". The split sits
    /// midway between this suite's own two literal values (90 and 250) with
    /// headroom on both sides, so it is not sensitive to their exact choice.
    private const int WantsGenuineMatchBelow = 150;

    private string? _frameFolder;
    private int _cardCount = 1;

    private RealFixtures? _fixtures;

    public string DisplayName => "Real";

    public void EnsureAvailable()
    {
        var (fixtures, reason) = RealFixtures.Load();
        if (fixtures is null)
        {
            RealArtifactGate.SkipOrFail(reason!);
            return;
        }

        _fixtures = fixtures;
    }

    /// No-op, unchanged since package I1: `CsvCollectionStore`,
    /// `NativeCsvExporter` and `MoxfieldCsvExporter` are real and need
    /// neither the index nor the Scryfall cache.
    public void EnsureCollectionAvailable()
    {
    }

    public ICardDetector CreateDetector(int cardCount)
    {
        _cardCount = cardCount;
        return new ContourCardDetector(NullLogger<ContourCardDetector>.Instance);
    }

    public IRectifier CreateRectifier() => new PerspectiveRectifier();

    /// Also where this set writes the frame content — see the type's own
    /// doc comment. Must run after <see cref="CreateFrameSourceFactory"/>
    /// (which records the folder) and after <see cref="CreateDetector"/>
    /// (which records the card count); every existing end-to-end case
    /// already calls them in that order, immediately before constructing
    /// the pipeline.
    public ICardIdentifier CreateIdentifier(IReadOnlyList<int> distances)
    {
        var fixtures = RequireFixtures();
        if (_frameFolder is null)
        {
            throw new InvalidOperationException(
                "RealImplementationSet.CreateIdentifier called before CreateFrameSourceFactory — " +
                "there is no frame folder to write real card imagery into.");
        }

        var wantsGenuineMatch = distances.Count > 0 && distances[0] < WantsGenuineMatchBelow;
        WriteFrameContent(fixtures, _frameFolder, _cardCount, wantsGenuineMatch);

        return fixtures.Identifier;
    }

    public IOracleCatalog CreateOracleCatalog() => RequireFixtures().Identifier;

    public ICollectionStore CreateCollectionStore(string path) =>
        new CsvCollectionStore(path, NullLogger<CsvCollectionStore>.Instance);

    public IReadOnlyList<ICollectionExporter> CreateExporters() =>
    [
        new NativeCsvExporter(),
        new MoxfieldCsvExporter(),
    ];

    /// Every existing end-to-end case calls this, then immediately
    /// `IFrameSourceFactory.CreateAsync`, BEFORE calling
    /// <see cref="CreateDetector"/>/<see cref="CreateIdentifier"/> — which is
    /// where the real frame content actually gets written (see
    /// <see cref="CreateIdentifier"/>'s own doc comment). If this returned
    /// an already-opened <see cref="FolderFrameSourceFactory"/> directly,
    /// its background decode loop would start ticking over
    /// <c>SyntheticFrames</c>' plain placeholder image immediately, and
    /// nothing would guarantee the pipeline's very first consumed frame
    /// (whatever happened to already be sitting in the source's
    /// capacity-1 channel) reflects OUR content rather than a stale
    /// placeholder decode — an intermittent race, confirmed by hitting it:
    /// several cases read as Unresolved roughly at random depending on
    /// scheduling. <see cref="DeferredFolderFrameSourceFactory"/> instead
    /// defers actually opening the folder (starting that loop) until the
    /// pipeline's own <c>ReadAsync</c> is first enumerated — which happens
    /// only after every Create* call, and therefore only after the real
    /// content is already on disk — making the race impossible rather than
    /// merely unlikely.
    public IFrameSourceFactory CreateFrameSourceFactory(string frameFolder, TimeSpan pollInterval)
    {
        _frameFolder = frameFolder;
        return new DeferredFolderFrameSourceFactory(frameFolder, pollInterval);
    }

    private RealFixtures RequireFixtures() => _fixtures ?? throw new InvalidOperationException(
        "RealImplementationSet: EnsureAvailable() must be called — and must return without skipping/failing " +
        "— before any Create* method runs.");

    /// Overwrites whichever image `SyntheticFrames.CreateTempDirectory`
    /// already wrote into `frameFolder` (there is exactly one, per every
    /// existing case's own call) with real generated content — never adds a
    /// second file, so the (not yet even opened — see
    /// <see cref="DeferredFolderFrameSourceFactory"/>) folder source's
    /// eventual path list stays a one-entry list; only the bytes at that
    /// path change.
    private static void WriteFrameContent(RealFixtures fixtures, string frameFolder, int cardCount, bool wantsGenuineMatch)
    {
        var existing = Directory.GetFiles(frameFolder);
        var path = existing.Length > 0 ? existing[0] : Path.Combine(frameFolder, "00.png");

        using var sourceCard = wantsGenuineMatch ? fixtures.SampleCardBgr.Clone() : MakeNonMatchingCardMat();
        using var frame = cardCount <= 1
            ? SyntheticFrameGenerator.Generate(sourceCard, HeightInches).Frame
            : MultiCardFrameGenerator.Generate(
                Enumerable.Repeat(sourceCard, cardCount).ToList(), ComputeGridCenters(cardCount), HeightInches);

        using var mat = FrameMat.ToMat(frame);

        // Write-temp-then-rename (DECISIONS.md's own storage-layer pattern,
        // reused here for the same reason): `FolderFrameSource`'s decode
        // loop is already running on its own timer the instant this method
        // gets called, so writing `path` directly risks the loop's next
        // tick reading it mid-write and faulting the WHOLE session on a
        // transient partial read — `FrameSourceException` completes the
        // channel permanently, not just for that one tick. `File.Move` with
        // overwrite onto the same volume never exposes a partial file.
        var extension = Path.GetExtension(path);
        var tempPath = Path.ChangeExtension(path, ".tmp" + extension);
        Cv2.ImWrite(tempPath, mat);
        File.Move(tempPath, path, overwrite: true);
    }

    /// Genuinely non-matching content for the "this tile must read as
    /// Unresolved" cases: a flat, near-black card-shaped patch — high
    /// contrast against the generator's own light mat background (so the
    /// real detector finds it just as reliably as a real card, the same way
    /// a real card's black border gives Canny a strong edge to find), but
    /// with no real artwork inside it. Composited through the SAME
    /// generator pipeline (keystone/grid placement, whole-frame blur,
    /// sensor noise, JPEG round trip) as a genuine match, so this is not an
    /// "easier" input — the added noise, layered onto an otherwise flat
    /// region, is what keeps the region's per-cell hash bits from
    /// collapsing to one deterministic pattern; it reads as an
    /// approximately random 1024-bit hash instead, whose expected Hamming
    /// distance to any one of the ~48k real entries is ~512 — nowhere near
    /// the committed okDistance of 240, by the same law of large numbers
    /// that makes two independent coin-flip sequences of length 1024 land
    /// close to 50% different bits almost every time.
    private static Mat MakeNonMatchingCardMat() =>
        new(RectifiedCard.CanonicalHeight, RectifiedCard.CanonicalWidth, MatType.CV_8UC3, new Scalar(20, 20, 20));

    /// See <see cref="CreateFrameSourceFactory"/>'s own doc comment for why
    /// this exists: it defers actually opening the folder (which is what
    /// starts <see cref="FolderFrameSource"/>'s background decode loop)
    /// until <see cref="ReadAsync"/> is first enumerated, rather than at
    /// <see cref="CreateAsync"/> time — by which point every Create* call,
    /// including the one that writes the real frame content, has already
    /// run.
    private sealed class DeferredFolderFrameSourceFactory : IFrameSourceFactory
    {
        private readonly string _folder;
        private readonly TimeSpan _interval;

        public DeferredFolderFrameSourceFactory(string folder, TimeSpan interval)
        {
            _folder = folder;
            _interval = interval;
        }

        public Task<IFrameSource> CreateAsync(ScanSettings settings, CancellationToken ct)
        {
            ct.ThrowIfCancellationRequested();
            IFrameSource source = new DeferredFolderFrameSource(_folder, _interval);
            return Task.FromResult(source);
        }
    }

    /// <see cref="Geometry"/> reports a fixed placeholder
    /// (1920x1080, unrotated) before the real folder ever opens — always
    /// correct in practice, since every frame this set ever writes (a
    /// genuine match or the non-matching patch) is generated at exactly
    /// that resolution (<see cref="SyntheticFrameGenerator.Generate"/>'s own
    /// default `FrameWidth`/`FrameHeight`). `ScanPipeline` reads
    /// `IFrameSource.Geometry` once, at construction — before any frame
    /// has flowed — so this must never be null or lazily-unknown.
    private sealed class DeferredFolderFrameSource : IFrameSource
    {
        private readonly string _folder;
        private readonly TimeSpan _interval;
        private FolderFrameSource? _inner;

        public DeferredFolderFrameSource(string folder, TimeSpan interval)
        {
            _folder = folder;
            _interval = interval;
        }

        public string Description => _inner?.Description ?? $"folder: {new DirectoryInfo(_folder).Name} (pending)";

        public FrameGeometry Geometry => _inner?.Geometry ?? new FrameGeometry(1920, 1080, RotationDegrees: 0);

        public async IAsyncEnumerable<CameraFrame> ReadAsync([EnumeratorCancellation] CancellationToken ct)
        {
            // Opens the folder — and starts FolderFrameSource's own
            // background decode loop — for the first time HERE, on first
            // enumeration, never at CreateAsync time. By now every Create*
            // call this test made has already run, so the real content is
            // already on disk.
            _inner = FolderFrameSource.Open(_folder, _interval);

            await foreach (var frame in _inner.ReadAsync(ct).ConfigureAwait(false))
            {
                yield return frame;
            }
        }

        public ValueTask DisposeAsync() => _inner?.DisposeAsync() ?? ValueTask.CompletedTask;
    }

    /// A simple flow layout for `cardCount` cards, generous enough to avoid
    /// the tight-gap contour-merging risk docs/history/orchestration-plan.md calls out
    /// for a real packed 3x3 (this suite only ever asks for 7, and only
    /// needs THOSE 7 reliably detected, not a maximally-realistic mat) —
    /// rows of up to 4, spread across the vertical middle 60% of the frame,
    /// each row's cards spread across the horizontal middle 76%.
    private static IReadOnlyList<(float XFrac, float YFrac)> ComputeGridCenters(int cardCount)
    {
        var maxCols = Math.Min(cardCount, 4);
        var rows = (int)Math.Ceiling(cardCount / (double)maxCols);
        var centers = new List<(float XFrac, float YFrac)>(cardCount);
        var remaining = cardCount;

        for (var r = 0; r < rows; r++)
        {
            var colsInRow = Math.Min(maxCols, remaining);
            remaining -= colsInRow;
            var yFrac = rows == 1 ? 0.5f : 0.2f + (0.6f * r / (rows - 1));

            for (var c = 0; c < colsInRow; c++)
            {
                var xFrac = colsInRow == 1 ? 0.5f : 0.12f + (0.76f * c / (colsInRow - 1));
                centers.Add((xFrac, yFrac));
            }
        }

        return centers;
    }

    /// Everything this set needs from disk, loaded once and gated together:
    /// the committed index (as both the real `HashCardIdentifier` and the
    /// raw `HashIndexData` for picking a sample entry), and one real
    /// Scryfall render pulled from the local cache for an artwork the index
    /// actually contains. `Load` never throws — a missing artifact comes
    /// back as `(null, reason)` for the caller to route through
    /// `RealArtifactGate`.
    private sealed class RealFixtures
    {
        public required HashCardIdentifier Identifier { get; init; }

        public required Mat SampleCardBgr { get; init; }

        public static (RealFixtures? Fixtures, string? SkipReason) Load()
        {
            if (!RepoPaths.TryFindRepoRoot(out var repoRoot))
            {
                return (null, "could not locate the repository root to find the committed index.");
            }

            var indexPath = Path.Combine(repoRoot!, "data", "index", "cards.lfidx");
            if (!File.Exists(indexPath))
            {
                return (null, $"committed hash index not present at \"{indexPath}\".");
            }

            var thresholdsPath = Path.Combine(repoRoot!, "data", "index", "thresholds.json");
            if (!File.Exists(thresholdsPath))
            {
                return (null, $"committed thresholds file not present at \"{thresholdsPath}\".");
            }

            var cacheDir = ResolveCacheDir();
            if (!Directory.Exists(cacheDir))
            {
                return (null, $"Scryfall image cache not present at \"{cacheDir}\" — card imagery can never be committed.");
            }

            // Loud on a genuinely corrupt/unsupported file — matches
            // ThresholdsFile.Load's own "loud rather than lenient" rule
            // (DECISIONS.md/ThresholdsFile's doc comment): a malformed
            // committed artifact is a real defect, not a "not present yet"
            // skip.
            ThresholdsFile.Load(thresholdsPath);

            var data = HashIndexFile.Read(indexPath);
            if (data.Entries.Count == 0)
            {
                return (null, $"committed hash index at \"{indexPath}\" has zero entries.");
            }

            var firstOracleId = data.OracleTable.Count > 0 ? data.OracleTable[0].OracleId : null;
            HashIndexEntry? sample = null;
            foreach (var entry in data.Entries)
            {
                if (entry.IsBasicLand || entry.OracleId == firstOracleId)
                {
                    continue;
                }

                if (File.Exists(ImageCache.GetImagePath(cacheDir, entry.ArtworkId)))
                {
                    sample = entry;
                    break;
                }
            }

            if (sample is null)
            {
                return (null, $"Scryfall image cache at \"{cacheDir}\" has no cached render for any indexed, " +
                    "non-land artwork — it may still be populating.");
            }

            var sampleImagePath = ImageCache.GetImagePath(cacheDir, sample.Value.ArtworkId);
            var sampleCardBgr = Cv2.ImRead(sampleImagePath, ImreadModes.Color);
            if (sampleCardBgr.Empty())
            {
                sampleCardBgr.Dispose();
                return (null, $"cached render at \"{sampleImagePath}\" failed to decode.");
            }

            var identifier = new HashCardIdentifier(data, NullLogger<HashCardIdentifier>.Instance);
            return (new RealFixtures { Identifier = identifier, SampleCardBgr = sampleCardBgr }, null);
        }

        /// A copy of `Tests/Lab/RoundTrip/RoundTripGateTests.ResolveCacheDir`'s
        /// resolution order — that method is internal to a sibling test
        /// assembly this project cannot reference, so this is a small,
        /// deliberate duplicate rather than a new production seam:
        /// `LOREFETCH_SCRYFALL_CACHE` first, then `~/LoreFetchData/scryfall-cache`,
        /// then (Windows only) `C:\LoreFetchData\scryfall-cache`.
        private static string ResolveCacheDir()
        {
            var overridePath = Environment.GetEnvironmentVariable("LOREFETCH_SCRYFALL_CACHE");
            if (!string.IsNullOrWhiteSpace(overridePath))
            {
                return overridePath;
            }

            var home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
            var homeCandidate = Path.Combine(home, "LoreFetchData", "scryfall-cache");
            if (Directory.Exists(homeCandidate))
            {
                return homeCandidate;
            }

            if (OperatingSystem.IsWindows())
            {
                var windowsCandidate = Path.Combine("C:" + Path.DirectorySeparatorChar, "LoreFetchData", "scryfall-cache");
                if (Directory.Exists(windowsCandidate))
                {
                    return windowsCandidate;
                }
            }

            return homeCandidate;
        }
    }
}
